// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub fn de_create_city_http_error(
    _response_status: u16,
    _response_headers: &::aws_smithy_runtime_api::http::Headers,
    _response_body: &[u8],
) -> std::result::Result<crate::operation::create_city::CreateCityOutput, crate::operation::create_city::CreateCityError> {
    #[allow(unused_mut)]
    let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body)
        .map_err(crate::operation::create_city::CreateCityError::unhandled)?;
    let generic = generic_builder.build();
    let error_code = match generic.code() {
        Some(code) => code,
        None => return Err(crate::operation::create_city::CreateCityError::unhandled(generic)),
    };

    let _error_message = generic.message().map(|msg| msg.to_owned());
    Err(match error_code {
        "CityAlreadyExists" => crate::operation::create_city::CreateCityError::CityAlreadyExists({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::CityAlreadyExistsBuilder::default();
                output = crate::protocol_serde::shape_city_already_exists::de_city_already_exists_json_err(_response_body, output)
                    .map_err(crate::operation::create_city::CreateCityError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::city_already_exists_correct_errors(output)
                    .build()
                    .map_err(crate::operation::create_city::CreateCityError::unhandled)?
            };
            if tmp.message.is_none() {
                tmp.message = _error_message;
            }
            tmp
        }),
        _ => crate::operation::create_city::CreateCityError::generic(generic),
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn de_create_city_http_response(
    _response_status: u16,
    _response_headers: &::aws_smithy_runtime_api::http::Headers,
    _response_body: &[u8],
) -> std::result::Result<crate::operation::create_city::CreateCityOutput, crate::operation::create_city::CreateCityError> {
    Ok({
        #[allow(unused_mut)]
        let mut output = crate::operation::create_city::builders::CreateCityOutputBuilder::default();
        output = crate::protocol_serde::shape_create_city::de_create_city(_response_body, output)
            .map_err(crate::operation::create_city::CreateCityError::unhandled)?;
        crate::serde_util::create_city_output_output_correct_errors(output)
            .build()
            .map_err(crate::operation::create_city::CreateCityError::unhandled)?
    })
}

pub fn ser_create_city_input(
    input: &crate::operation::create_city::CreateCityInput,
) -> Result<::aws_smithy_types::body::SdkBody, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_create_city_input::ser_create_city_input_input(&mut object, input)?;
    object.finish();
    Ok(::aws_smithy_types::body::SdkBody::from(out))
}

pub(crate) fn de_create_city(
    value: &[u8],
    mut builder: crate::operation::create_city::builders::CreateCityOutputBuilder,
) -> Result<crate::operation::create_city::builders::CreateCityOutputBuilder, ::aws_smithy_json::deserialize::error::DeserializeError> {
    let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
    let tokens = &mut tokens_owned;
    ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    loop {
        match tokens.next().transpose()? {
            Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
            Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => match key.to_unescaped()?.as_ref() {
                "cityId" => {
                    builder = builder.set_city_id(
                        ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                    );
                }
                _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?,
            },
            other => {
                return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!(
                    "expected object key or end object, found: {:?}",
                    other
                )))
            }
        }
    }
    if tokens.next().is_some() {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
            "found more JSON tokens after completing parsing",
        ));
    }
    Ok(builder)
}
