// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::types::_city_coordinates::CityCoordinates;

pub use crate::types::_city_summary::CitySummary;

mod _city_coordinates;

mod _city_summary;

/// Builders
pub mod builders;

/// Error types that the service can respond with.
pub mod error;
