[workspace]
members = [
    "weather-crate",
    "weather-crate-client-sdk",
    "weather-crate-server-sdk",
]
exclude = [
    "model/build/codegen/weather-crate-server-sdk/rust-server-codegen",
    "model/build/codegen/weather-crate-client-sdk/rust-codegen",
]
