// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::types::_city_coordinates::CityCoordinatesBuilder;

pub use crate::types::_city_summary::CitySummaryBuilder;
