// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Types for the `CreateCity` operation.
pub mod create_city;

/// Types for the `DeleteCity` operation.
pub mod delete_city;

/// Types for the `GetCity` operation.
pub mod get_city;

/// Types for the `GetCurrentTime` operation.
pub mod get_current_time;

/// Types for the `GetForecast` operation.
pub mod get_forecast;

/// Types for the `ListCities` operation.
pub mod list_cities;
