// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteCityOutput {}
impl DeleteCityOutput {
    /// Creates a new builder-style object to manufacture [`DeleteCityOutput`](crate::operation::delete_city::DeleteCityOutput).
    pub fn builder() -> crate::operation::delete_city::builders::DeleteCityOutputBuilder {
        crate::operation::delete_city::builders::DeleteCityOutputBuilder::default()
    }
}

/// A builder for [`DeleteCityOutput`](crate::operation::delete_city::DeleteCityOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DeleteCityOutputBuilder {}
impl DeleteCityOutputBuilder {
    /// Consumes the builder and constructs a [`DeleteCityOutput`](crate::operation::delete_city::DeleteCityOutput).
    pub fn build(self) -> crate::operation::delete_city::DeleteCityOutput {
        crate::operation::delete_city::DeleteCityOutput {}
    }
}
