// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetCurrentTime`](crate::operation::get_current_time::builders::GetCurrentTimeFluentBuilder) operation.
    ///
    /// - The fluent builder takes no input, just [`send`](crate::operation::get_current_time::builders::GetCurrentTimeFluentBuilder::send) it.
    /// - On success, responds with [`GetCurrentTimeOutput`](crate::operation::get_current_time::GetCurrentTimeOutput) with field(s):
    ///   - [`time(DateTime)`](crate::operation::get_current_time::GetCurrentTimeOutput::time): (undocumented)
    /// - On failure, responds with [`SdkError<GetCurrentTimeError>`](crate::operation::get_current_time::GetCurrentTimeError)
    pub fn get_current_time(&self) -> crate::operation::get_current_time::builders::GetCurrentTimeFluentBuilder {
        crate::operation::get_current_time::builders::GetCurrentTimeFluentBuilder::new(self.handle.clone())
    }
}
