// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetCity`](crate::operation::get_city::builders::GetCityFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`city_id(impl Into<String>)`](crate::operation::get_city::builders::GetCityFluentBuilder::city_id) / [`set_city_id(Option<String>)`](crate::operation::get_city::builders::GetCityFluentBuilder::set_city_id):<br>required: **true**<br>(undocumented)<br>
    /// - On success, responds with [`GetCityOutput`](crate::operation::get_city::GetCityOutput) with field(s):
    ///   - [`name(String)`](crate::operation::get_city::GetCityOutput::name): (undocumented)
    ///   - [`coordinates(CityCoordinates)`](crate::operation::get_city::GetCityOutput::coordinates): (undocumented)
    /// - On failure, responds with [`SdkError<GetCityError>`](crate::operation::get_city::GetCityError)
    pub fn get_city(&self) -> crate::operation::get_city::builders::GetCityFluentBuilder {
        crate::operation::get_city::builders::GetCityFluentBuilder::new(self.handle.clone())
    }
}
