// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListCities`](crate::operation::list_cities::builders::ListCitiesFluentBuilder) operation.
    /// This operation supports pagination; See [`into_paginator()`](crate::operation::list_cities::builders::ListCitiesFluentBuilder::into_paginator).
    ///
    /// - The fluent builder is configurable:
    ///   - [`next_token(impl Into<String>)`](crate::operation::list_cities::builders::ListCitiesFluentBuilder::next_token) / [`set_next_token(Option<String>)`](crate::operation::list_cities::builders::ListCitiesFluentBuilder::set_next_token):<br>required: **false**<br>(undocumented)<br>
    ///   - [`page_size(i32)`](crate::operation::list_cities::builders::ListCitiesFluentBuilder::page_size) / [`set_page_size(Option<i32>)`](crate::operation::list_cities::builders::ListCitiesFluentBuilder::set_page_size):<br>required: **false**<br>(undocumented)<br>
    /// - On success, responds with [`ListCitiesOutput`](crate::operation::list_cities::ListCitiesOutput) with field(s):
    ///   - [`next_token(Option<String>)`](crate::operation::list_cities::ListCitiesOutput::next_token): (undocumented)
    ///   - [`items(Vec::<CitySummary>)`](crate::operation::list_cities::ListCitiesOutput::items): (undocumented)
    /// - On failure, responds with [`SdkError<ListCitiesError>`](crate::operation::list_cities::ListCitiesError)
    pub fn list_cities(&self) -> crate::operation::list_cities::builders::ListCitiesFluentBuilder {
        crate::operation::list_cities::builders::ListCitiesFluentBuilder::new(self.handle.clone())
    }
}
