// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CreateCityOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub city_id: ::std::string::String,
}
impl CreateCityOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn city_id(&self) -> &str {
        use std::ops::Deref;
        self.city_id.deref()
    }
}
impl CreateCityOutput {
    /// Creates a new builder-style object to manufacture [`CreateCityOutput`](crate::operation::create_city::CreateCityOutput).
    pub fn builder() -> crate::operation::create_city::builders::CreateCityOutputBuilder {
        crate::operation::create_city::builders::CreateCityOutputBuilder::default()
    }
}

/// A builder for [`CreateCityOutput`](crate::operation::create_city::CreateCityOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CreateCityOutputBuilder {
    pub(crate) city_id: ::std::option::Option<::std::string::String>,
}
impl CreateCityOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn city_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.city_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_city_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.city_id = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_city_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.city_id
    }
    /// Consumes the builder and constructs a [`CreateCityOutput`](crate::operation::create_city::CreateCityOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`city_id`](crate::operation::create_city::builders::CreateCityOutputBuilder::city_id)
    pub fn build(self) -> ::std::result::Result<crate::operation::create_city::CreateCityOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::create_city::CreateCityOutput {
            city_id: self.city_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "city_id",
                    "city_id was not specified but it is required when building CreateCityOutput",
                )
            })?,
        })
    }
}
